version: "3"

services:
   flaskai:
     image: "flaskai:0.01"
     restart: unless-stopped
    #  depends_on:
    #    - mariadb
     ports:
       - '5000:5000'
    #  links:
    #    - mariadb
     volumes:
       - /home/ubuntu/isCat:/models:z
#       - ../secrets:/var/www/secrets:z
#       - ./scripts:/var/www/scripts:z
      #  - ./logs:/var/www/logs:z

# docker run -it -p 5000:5000 -v "/home/ubuntu/fastai/models:/models" fastai/fastai /bin/bash